### PR TITLE
minor fix and support for keywords as attr/style-prop values

### PR DESCRIPTION
**Pull request by ul**

### CODE REVIEW

**Comment by ul** [comment]
Need to say that develop branch almost completely broken for me.
Diffing has problem, when text node is replaced with non-string, throwing exception at https://github.com/aaronc/freactive/blob/develop/src-cljs/freactive/dom.cljs#L486 , because text nodes does not carry freactive's element state. It should be fixed easely by adding check to https://github.com/aaronc/freactive/blob/develop/src-cljs/freactive/dom.cljs#L530, but then I have problems that varous subtrees of my dom are not rendered. And they are not rendered with disabled diffing too. Some of rendered nodes has `class="null"`. This happens silently, without exceptions, so i'm not sure where to dig. If you could give me any clues, I will do my best to help to fix those issues.

**Comment by aaronc** [comment]
I'll try to take a look at this as soon as I get a chance -been a little busy, but hopefully this weekend. In general though, it looks good.

**Comment by aaronc** [comment]
Sorry... I've been away from this project for a while, but I have a little bit of time to look at it this week and come April I should be a little more focused on it when I'm doing front-end dev again. Are you still working on it? Thanks for this pull request.

**Comment by ul** [comment]
Salute! I ran into some problems with freactive which I couldn't fix by myself without deep meditation and decided to wait until I will have enough free time to dive into the code, but these months were surprisingly busy. I'm not sure that I will have a chance to use freactive for web in the nearest time, but will keep my eye on and return to it when it will be possible.

**Pull request merged**
